config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  # get 'bookings/new'
  # get 'bookings/create'
  # get 'bookings/edit'
  # get 'bookings/destroy'
  # get 'cars/index'

  root to: 'cars#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources  :cars

  resources :cars do
    resources :bookings, only: [:show, :create, :update, :destroy]
  end

  namespace :users do
    resources :cars, only: [:index]
  end
  # test xxxx
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user_id, presence: true
  validates :car_id, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings
  #has_many :users, through: :bookings
  has_many :booked_users, through: :bookings, source: :user
  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :location_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #after_create :send_welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #For OmniAuth
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :bookings
  has_many :cars
  has_many :rented_cars, through: :bookings, source: :car

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

  #def send_welcome_email
  #  UserMailer.welcome(self).deliver_now
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  after_action  :store_location

  def store_location
    if (request.fullpath != "/users/sign_in" &&
        request.fullpath != "/users/sign_up" &&
        request.fullpath !~ Regexp.new("\\A/users/password.*\\z") &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    if (session[:previous_url] == root_path)
      super
    else
      session[:previous_url] || root_path
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
    #This means @bookings = Booking.where("user_id = ?", current_user.id)

    @cars = Car.includes(:bookings).where(bookings: {user_id: current_user.id})
    #There are some other ways to implement the above. I left memo.
    # 1st one(tricky): @cars = @bookings.map(&:car)
    # 2nd one: @cars = []
    #          @cars = @bookings.map do |booking|
    #            booking.car
    #          end
    # 3rd one: @cars = []
    #          @bookings.each do |b|
    #            @cars << Car.where('id = ?', b.car_id).first
    #          end
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id].to_i)
    #recieve @car from cars/:car_id/show
    ## show page has an instance of @car
    #@user = current_user
  end

  def create
    # raise
    @car = Car.find(params[:car_id].to_i)
    @booking = Booking.new(strong_params)
    @booking.user = current_user
    #create Booking
    if @booking.save
      redirect_to car_booking_path(@car.id, @booking.id)
    else
      render 'cars/show'
    end
  end

  def show
    @car = Car.find(params[:car_id].to_i)
    if params[:id]
      @booking = Booking.find(params[:id].to_i)
    else
      @booking = Booking.new
    end
  end


  def update
  end

  def destroy
    booking = Booking.find(params[:id])
    if booking.user == current_user
      booking.destroy
      redirect_to bookings_index_path
    else
      # throw pop-up with FU message
      redirect_to root_path
    end
  end


  private

  def strong_params
    params.require(:booking).permit(:start_date, :end_date, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:search_text]
      @searched = true
      @cars = Car.where('lower(name) LIKE lower(?) OR lower(model) LIKE lower(?) OR lower(make) LIKE lower(?) OR lower(location) LIKE lower(?)', "%#{params[:search_text]}%", "%#{params[:search_text]}%", "%#{params[:search_text]}%", "%#{params[:search_text]}%")
    elsif params[:end_date]
      #implement
      @searched = true
      @cars = []
      Car.all.each do |car|
        if car.bookings.all? do |booking|
             booking.end_date.to_s < params[:start_date] || booking.start_date.to_s > params[:end_date]
           end
           @cars << car
        end
      end
    else
      @cars = Car.all
      @searched = false
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @hash = Gmaps4rails.build_markers(@car) do |car, marker|
      marker.lat car.latitude
      marker.lng car.longitude
      # marker.infowindow render_to_string(partial: "/cars/map_box", locals: { car: car })
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(strong_params)
    @car.user = current_user

    if @car.save
      redirect_to users_cars_path
    else
      render :new
    end
  end

  # Todo Edit Here to implement Car Information Edit!

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(strong_params)
      redirect_to users_cars_path
    else
      render "edit"
    end
  end

  # Todo Edit Here to implement Car Information Destroy!
  def destroy
    car = Car.find(params[:id])
    if car.user_id == current_user.id
      car.destroy
      redirect_to users_cars_path
    else
      # throw pop-up with FU message
      redirect_to users_cars_path
    end
  end

  private

  def strong_params
    params.require(:car).permit(:name, :make, :year, :color, :seats, :location, :transmission, :price, :photo, :photo_cache)
  end
end

app/controllers/users/cars_controller.rb
class Users::CarsController < ApplicationController
  #
  #This is for Logined User

  def index
    @cars = Car.where(user_id: current_user.id)
  end

  # def show
  #   @car = Car.find(params[:id])
  #
  #   @hash = Gmaps4rails.build_markers(@car) do |car, marker|
  #     marker.lat car.latitude
  #     marker.lng car.longitude
  #     # marker.infowindow render_to_string(partial: "/cars/map_box", locals: { car: car })
  #   end
  # end
  #
  #
  #
  # def create
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
  def index
    @Cars = Car.where("user_id = ?", current_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<!-- <p class="text-muted">Find me in app/views/bookings/index.html.erb</p> -->
<!-- Prefix      Verb     URI Pattern                               Controller#Action -->
<!-- car_booking GET      /cars/:car_id/bookings/:id(.:format)      bookings#show -->
<!-- You have @bookings (Your bookings record) here. -->

<h1 class="text-center">Your Booking Information</h1>
<div class="">
  <div class="row">

<!--[From Here] Changed from usual index page -->
    <% @bookings.each do |booking| %>
      <% car = booking.car %>
        <div class="col-xs-12 col-sm-4 col-md-3">
          <%= link_to car_booking_path(car.id, booking.id) do %>

          <div class="card-body">
            <% if car.photo.url %>
            <div class="card-picture text-center" style="background-image: url(<%= car.photo.url %>);"></div>
          <% else %>
            <div class="card-picture text-center" style="background-image: url('https://s-media-cache-ak0.pinimg.com/736x/b0/60/7a/b0607ac790b5460db4566fce20caf802.jpg')"></div>
            <% end %>

            <% car_description = "#{car.year} #{car.make} #{car.model}" %>
            <% @currency = "€" %>
            <% price = "#{@currency}#{car.price.to_i}" %>
            <% star = "👍 "  %>

            <div class="card-footer">
              <ul class="list-inline">
                <li><%= car_description %></li>
                <!-- <li class="price"><%#= price %></li> -->

              </ul>

              <div class="booking-date">
                <p>Dates:  <%= booking.start_date.to_s :month_day_comma_year %> >> <%= booking.end_date.to_s :month_day_comma_year %></p>

              </div>
              <!-- <div class="share-links">
                <a href="#" class="share-link bg-facebook">
                  <i class="fa fa-facebook"></i>
                </a>
                <a href="#" class="share-link bg-twitter">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="#" class="share-link bg-email">
                  <i class="fa fa-envelope-o"></i>
                </a>
              </div> -->
            </div>
          </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>

app/views/bookings/show.html.erb
<h1 class="text-center"><%= @car.name %></h1>
<h2 class="show-title">Thank you for your booking!</h2>



  <div class="container">
    <div class="row">

     <div class="col-xs-12 col-sm-3 col-md-4 picture-box">
      <div class="show-picture">
        <% if @car.photo %>
          <%= cl_image_tag @car.photo, height: 300, width: 400, crop: :fill, class: "img-responsive car-picture" %>
        <% end %>
      </div>
    </div>

      <div class="col-xs-12 col-sm-3 col-md-4">
         <div class="detail-box">
              <div class="detail">
              <!-- <ul class="show-list">
                  <li><strong>Make: </strong> <%= @car.make %></li>
                  <li><strong>Model: </strong><%= @car.model  %></li>
                  <li><strong>Year: </strong>   <%= @car.year  %></li>
                  <li><strong>Color: </strong><%= @car.color  %></li>
                  <li><strong>Seats: </strong>  <%= @car.seats  %></li>
                  <li><strong>Location: </strong> <%= @car.location  %></li>
                  <li><strong>Transmission: </strong><%= @car.transmission  %></li>
                  <li><strong>Price/day: €</strong><%#= "#{@car.price.to_i}"  %></li>
               </ul> -->
              <% [:make, :model, :year, :color, :seats, :location, :transmission].each do |a| %>
                <dl class="dl-horizontal show-list">
                  <dt><%= "#{a.to_s.capitalize}: " %></dt>
                  <dd><%= @car.send a %></dd>
                </dl>
              <% end %>
                <dl class="dl-horizontal show-list">
                  <dt>Price/day: </dt>
                  <dd><%= "€#{@car.price.to_i}" %></dd>
                </dl>
          </div>
        </div>
      </div>

  <div class="col-xs-12 col-sm-3 col-md-4">
      <% if @booking.user == current_user %>
          <div class="detail-box">
          <div class="detail">
            <!-- <p class="booking-details">Booking Details</p> -->

          <dl class="dl-horizontal show-list">
            <dt>Pick-up Date: </dt>
            <dd><%= @booking.start_date.to_s :month_day_comma_year %></dd>
          </dl>
          <dl class="dl-horizontal show-list">
            <dt>Drop-off Date: </dt>
            <dd><%= @booking.end_date.to_s :month_day_comma_year %></dd>
          </dl>
          <dl class="dl-horizontal show-list">
            <dt>Price/day: </dt>
            <dd><%= "€#{@currency}#{@car.price.to_i}" %></dd>
          </dl>
           <dl class="dl-horizontal show-list">
            <dt>Total: </dt>
            <dd><%= "€#{@car.price.to_i * (@booking.end_date - @booking.start_date).to_i }" %></dd>
          </dl>
        <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="action-box">
    <div class="pull-right booking-link"><%= link_to 'Your Boooking List', bookings_index_path %></div>
  </div>

  <div class="action-box">
    <%= simple_form_for [@car] do |f| %>
    
    <%= link_to "Cancel this Booking", car_booking_path(@booking.car_id, @booking.id), method: :delete, class: "btn btn-danger"  %>
    
    <% end %>
  </div>

</div>

app/views/cars/edit.html.erb
<div class="container">

  <h2><%= link_to "Back to Your Listings", users_cars_path,  {class: "btn btn-primary"} %></h2>

  <div class="jumbutron">
  <h1 class="text-center">Edit your Xcar</h1>
  </div>

  <div class="contact-form">
    <%= simple_form_for @car do |f| %>
    <%= f.input :name %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :color %>
    <%= f.input :seats %>
    <%= f.input :location %>
    <%= f.input :transmission %>
    <%= f.input :price %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <div class="form-actions text-right">
    <%= f.button :submit, "Change it!", {class:"btn-success"} %>
    </div>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
<!-- BANNER -->
<% if @searched == false %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'xcar_banner.jpg' %>');">
    <div class="banner-content">
      <h1>Xcars</h1>
      <p>OWN THE EXPERIENCE, NOT THE CAR</p>
      <!-- <a class="btn btn-warning btn-lg">BOOK IT</a> -->
    </div>
  </div>


<!-- LINK TO ACTION -->
<div class="container text-center padded features">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= link_to image_tag("booking_icon.png"), bookings_index_path %>
      <h2>Manage Booking</h2>
      <p>Request,change and cancel booking</p>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= link_to image_tag("renting_icon.png"), users_cars_path %>
      <h2>Manage your Cars</h2>
      <p>Become a host and rent out your car</p>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= image_tag "experience_icon.png" %>
      <h2>Share Your Story</h2>
      <p>Share your Xcar story here</p>
    </div>
  </div>
</div>
<% end %>

<!-- AVAILABLE CARS LIST-->
<div class="container">
  <div class="row">
    <% @cars.each do |car| %>
      <div class="col-xs-12 col-sm-4 card-container">
        <!-- insert <div class="card"> -->
        <% if car.photo.url %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= car.photo.url %>');">
        <% else %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://s-media-cache-ak0.pinimg.com/736x/b0/60/7a/b0607ac790b5460db4566fce20caf802.jpg');">
        <% end %>

        <% car_description = "#{car.year} #{car.make} #{car.model}" %>
        <% @currency = "€" %>
        <% price = "#{@currency}#{car.price.to_i}" %>
          <div class="card-category"><%= price %></div>
          <div class="card-description">
            <h2><%= car.name  %></h2>
            <p><%= car_description %></p>
          </div>
           <!-- <img class="card-user avatar" src="<%#= car.user.photo.url %>"> -->
          <%= link_to "",  car_path(car) , class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- NEWS LETTER -->
<% if @searched == false %>
<div class="text-center padded" id="newsletter">
  <h2>Get news from us</h2>
  <p>Leave us your mail and get news from us</p>
  <form class="form-inline">
    <input type="email" placeholder="xcars@x.car" class="form-control">
    <input type="submit" value="Subscribe" class="btn btn-primary btn-bordered btn-bordered-primary">
  </form>
</div>
<% end %>

app/views/cars/new.html.erb
<div class="container">
  <div class="row">
      <div class="form-login contact-form">
        <h1 class="text-center">Register New Car</h1>
          <%= simple_form_for @car do |f| %>
          <%= f.input :name %>
          <%= f.input :make %>
          <%= f.input :model %>
          <%= f.input :year %>
          <%= f.input :color %>
          <%= f.input :seats %>
          <%= f.input :location %>
          <%= f.input :transmission %>
          <%= f.input :price %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit, "Register", {class:"btn-primary btn-register"} %>
        <% end %>
      </div>
  </div>
</div>

app/views/cars/show.html.erb
<h1 class="text-center"><%= @car.name %></h1>

<!--
<div class="text-center padded">
  <%#= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>
 -->
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-sm-3 col-md-4 picture-box">
      <div class="show-picture">
        <% if @car.photo %>
          <%= cl_image_tag @car.photo, height: 300, width: 400, crop: :fill, class: "img-responsive car-picture" %>
        <% end %>
      </div>
    </div>
    <!-- end of first row element -->

    <div class="col-xs-12 col-sm-3 col-md-4">
      <div class="detail-box">
        <div class="detail">
        <!-- <ul class="show-list">
            <li><strong>Make: </strong> <%= @car.make %></li>
            <li><strong>Model: </strong><%= @car.model  %></li>
            <li><strong>Year: </strong>   <%= @car.year  %></li>
            <li><strong>Color: </strong><%= @car.color  %></li>
            <li><strong>Seats: </strong>  <%= @car.seats  %></li>
            <li><strong>Location: </strong> <%= @car.location  %></li>
            <li><strong>Transmission: </strong><%= @car.transmission  %></li>
            <li><strong>Price/day: €</strong><%#= "#{@car.price.to_i}"  %></li>
         </ul> -->
            <% [:make, :model, :year, :color, :seats, :location, :transmission].each do |a| %>
              <dl class="dl-horizontal show-list">
                <dt><%= "#{a.to_s.capitalize}: " %></dt>
                <dd><%= @car.send a %></dd>
              </dl>
            <% end %>
            <dl class="dl-horizontal show-list">
                <dt>Price/day: </dt>
                <dd><%= "€#{@car.price.to_i}" %></dd>
              </dl>
        </div>
      </div>
    </div>
    <!-- end of second row element -->


    <% if user_signed_in? && current_user == @car.user %>

      <div class="col-xs-12 col-sm-3 col-md-4">
        <h2>You are owner of this car!</h2>

<!-- edit code goes in here -->

         <%= link_to "Edit this Listing", edit_car_path(@car.id), class: "btn btn-info"  %>


<!-- delete code goes in here -->
          <%= link_to "Remove this Listing", car_path(@car.id), method: :delete, class: "btn btn-danger"  %>


       <!-- end of conditional first element -->
      </div>
    <% else %>

      <!--  THis is for Demo Deta -->
      <div id="invisible" data-rubyvar1="<%= "2017-08-01" %>" data-rubyvar2="<%= "2017-08-02" %>"
         data-rubyvar3="<%= "2017-08-03" %>" data-rubyvar4="<%= "2017-08-04" %>" data-rubyvar10="<%= "2017-08-10" %>"
         data-rubyvar11="<%= "2017-08-11" %>" data-rubyvar12="<%= "2017-08-12" %>" data-rubyvar13="<%= "2017-08-13" %>"
         data-rubyvar14="<%= "2017-08-14" %>" data-rubyvar14="<%= "2017-08-15" %>"
      </div>


      <div class="col-xs-12 col-sm-3 col-md-4 date-box">
        <div class="date-section-container">
          <%= simple_form_for [@car, @booking] do |f| %>
            <%= f.input :start_date, as: :string, input_html: { class: 'datepicker' } %>
            <%= f.input :end_date, as: :string, input_html: { class: 'datepicker' } %>
            <%= f.input :car_id, :as => :hidden, :input_html => { :value => @car.id }  %>
            <%= f.submit "Book this car!", class: "btn btn-primary", method: :post %>
          <% end %>
        </div>
      </div>
<!-- To Here: [07/12 Evening] Kouhei Changed this part Implemented buttons for Owner -->
    <% end %>
  <!-- end of if -->
  </div>
  <!-- end of row -->

  <div class="row">
    <div class="col-xs-12 map-container">
      <div id="map" style="width: 100%; height: 400px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        <% end %>
      <% end %>
          <!-- google map -->
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>XCARS</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <div class="page-wrap">
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
      <%= yield %>
    </div>

    <%= render "shared/footer" %>

    <!-- [...] -->
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%#= javascript_include_tag "https://maps.google.com/maps/api/js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag "application" %>

    <%= yield(:after_js) %>

  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-youtube"></i></a></li>
          <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <a href="/" class="navbar-wagon-brand">
          <%= image_tag "xcarrental2.jpg" %>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/users/cars/index.html.erb
<!-- <h2>Views/Users/Cars/index.html.erb</h2> -->

<h1 class="text-center">Your-Listing</h1>

<div class="text-center">
<h2><%= link_to "Register New Car", new_car_path, {class: "btn btn-primary"} %></h2>
</div>

<div class="">
  <div class="row">

    <% @cars.each do |car| %>

      <div class="col-xs-12 col-sm-4 col-md-3">
        <%= link_to car_path(car) do %>
          <div class="card-body">

            <% if car.photo.url %>
              <div class="card-picture text-center" style="background-image: url(<%= car.photo.url %>);"></div>
            <% else %>
              <div class="card-picture text-center" style="background-image: url('https://s-media-cache-ak0.pinimg.com/736x/b0/60/7a/b0607ac790b5460db4566fce20caf802.jpg')"></div>
            <% end %>

            <% car_description = "#{car.year} #{car.make} #{car.model}" %>
            <% currency = "€" %>
            <% price = "#{currency}#{car.price.to_i}" %>
            <% star = "👍 "  %>

            <div class="card-footer">
              <ul class="list-inline">
                <li><%= car_description %></li>
                <li class="price"><%= price %></li>
                <li class="rating"><%= star * rand(1..4) %></li>
              </ul>
              <div class="share-links">
                <a href="#" class="share-link bg-facebook">
                  <i class="fa fa-facebook"></i>
                </a>
                <a href="#" class="share-link bg-twitter">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="#" class="share-link bg-email">
                  <i class="fa fa-envelope-o"></i>
                </a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<!-- <h2>Views/Users/Cars/index.html.erb</h2> -->

<h1 class="text-center">Your-Listing</h1>

<div class="block-center">
<h2><%= link_to "Register New Car", new_car_path, {class: "btn btn-primary"} %></h2>
</div>
<div class="">
  <div class="row">

    <% @cars.each do |car| %>

      <div class="col-xs-12 col-sm-4 col-md-3">
        <%= link_to car_path(car) do %>
          <div class="card-body">

            <% if car.photo.url %>
              <div class="card-picture text-center" style="background-image: url(<%= car.photo.url %>);"></div>
            <% else %>
              <div class="card-picture text-center" style="background-image: url('https://s-media-cache-ak0.pinimg.com/736x/b0/60/7a/b0607ac790b5460db4566fce20caf802.jpg')"></div>
            <% end %>

            <% car_description = "#{car.year} #{car.make} #{car.model}" %>
            <% currency = "€" %>
            <% price = "#{currency}#{car.price.to_i}" %>
            <% star = "👍 "  %>

            <div class="card-footer">
              <ul class="list-inline">
                <li><%= car_description %></li>
                <li class="price"><%= price %></li>
                <li class="rating"><%= star * rand(1..4) %></li>
              </ul>
              <div class="share-links">
                <a href="#" class="share-link bg-facebook">
                  <i class="fa fa-facebook"></i>
                </a>
                <a href="#" class="share-link bg-twitter">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="#" class="share-link bg-email">
                  <i class="fa fa-envelope-o"></i>
                </a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>